migrate(
  (app) => {
    // 1. Coleção: carrier_evaluations (Avaliações estruturadas de motorista e/ou veículo)
    const evalCol = new Collection({
      name: 'carrier_evaluations',
      type: 'base',
      listRule: "@request.auth.id != ''",
      viewRule: "@request.auth.id != ''",
      createRule: "@request.auth.id != ''",
      updateRule: "@request.auth.id != ''",
      deleteRule: "@request.auth.id != ''",
      fields: [
        { name: 'transport_order_number', type: 'text' },
        { name: 'sap_transport_number', type: 'text' },
        {
          name: 'target_type',
          type: 'select',
          required: true,
          values: ['MOTORISTA', 'VEICULO', 'MOTORISTA_VEICULO', 'TRANSPORTADORA', 'TRANSPORTE'],
          maxSelect: 1,
        },
        { name: 'driver_id', type: 'text' },
        { name: 'driver_name', type: 'text' },
        { name: 'driver_document', type: 'text' },
        { name: 'vehicle_plate', type: 'text' },
        { name: 'vehicle_type', type: 'text' },
        { name: 'carrier_name', type: 'text' },
        { name: 'itinerary_code', type: 'text' },
        { name: 'customer_name', type: 'text' },
        {
          name: 'origin_type',
          type: 'select',
          required: true,
          values: [
            'CLIENTE',
            'TRANSPORTE_LOGISTICA',
            'EXPEDICAO',
            'FATURAMENTO',
            'PORTARIA',
            'COMERCIAL',
            'REPRESENTANTE_VENDEDOR',
            'SEGURANCA',
            'MOTORISTA',
            'GESTOR',
            'SISTEMA_IA',
          ],
          maxSelect: 1,
        },
        { name: 'origin_user_email', type: 'text' },
        { name: 'origin_user_name', type: 'text' },
        { name: 'evaluation_date', type: 'date' },
        {
          name: 'operational_moment',
          type: 'select',
          values: [
            'DURANTE_OPERACAO',
            'APOS_CARREGAMENTO',
            'APOS_ENTREGA',
            'RETORNO_CLIENTE',
            'APOS_OCORRENCIA',
            'CONSULTA_HISTORICA',
          ],
          maxSelect: 1,
        },
        // Critérios Motorista (1-5 cada)
        { name: 'driver_pontualidade', type: 'number', min: 0, max: 5 },
        { name: 'driver_cumprimento_orientacoes', type: 'number', min: 0, max: 5 },
        { name: 'driver_relacionamento_interno', type: 'number', min: 0, max: 5 },
        { name: 'driver_relacionamento_cliente', type: 'number', min: 0, max: 5 },
        { name: 'driver_comunicacao', type: 'number', min: 0, max: 5 },
        { name: 'driver_disponibilidade', type: 'number', min: 0, max: 5 },
        { name: 'driver_colaboracao', type: 'number', min: 0, max: 5 },
        { name: 'driver_postura_profissional', type: 'number', min: 0, max: 5 },
        { name: 'driver_cuidado_carga', type: 'number', min: 0, max: 5 },
        { name: 'driver_cumprimento_itinerario', type: 'number', min: 0, max: 5 },
        { name: 'driver_qualidade_atendimento', type: 'number', min: 0, max: 5 },
        { name: 'driver_tratamento_ocorrencias', type: 'number', min: 0, max: 5 },
        { name: 'driver_regras_seguranca', type: 'number', min: 0, max: 5 },
        { name: 'driver_documentacao', type: 'number', min: 0, max: 5 },
        { name: 'driver_qualidade_geral', type: 'number', min: 0, max: 5 },
        { name: 'driver_avg_score', type: 'number', min: 0, max: 5 },
        {
          name: 'driver_recommendation',
          type: 'select',
          values: ['SIM', 'SIM_COM_RESSALVAS', 'NAO'],
          maxSelect: 1,
        },
        // Critérios Veículo (1-5 cada)
        { name: 'vehicle_conservacao', type: 'number', min: 0, max: 5 },
        { name: 'vehicle_limpeza', type: 'number', min: 0, max: 5 },
        { name: 'vehicle_condicoes_aparentes', type: 'number', min: 0, max: 5 },
        { name: 'vehicle_adequacao_carga', type: 'number', min: 0, max: 5 },
        { name: 'vehicle_carroceria', type: 'number', min: 0, max: 5 },
        { name: 'vehicle_protecao_carga', type: 'number', min: 0, max: 5 },
        { name: 'vehicle_lona', type: 'number', min: 0, max: 5 },
        { name: 'vehicle_amarracao', type: 'number', min: 0, max: 5 },
        { name: 'vehicle_capacidade', type: 'number', min: 0, max: 5 },
        { name: 'vehicle_documentacao', type: 'number', min: 0, max: 5 },
        { name: 'vehicle_condicoes_operacionais', type: 'number', min: 0, max: 5 },
        { name: 'vehicle_regras_internas', type: 'number', min: 0, max: 5 },
        { name: 'vehicle_avg_score', type: 'number', min: 0, max: 5 },
        // Justificativas e observações
        { name: 'justification_critical', type: 'text' },
        { name: 'general_notes', type: 'text' },
        { name: 'tags_json', type: 'json' },
        { name: 'created', type: 'autodate', onCreate: true, onUpdate: false },
        { name: 'updated', type: 'autodate', onCreate: true, onUpdate: true },
      ],
      indexes: [
        'CREATE INDEX idx_careval_driver ON carrier_evaluations (driver_id)',
        'CREATE INDEX idx_careval_plate ON carrier_evaluations (vehicle_plate)',
        'CREATE INDEX idx_careval_sap ON carrier_evaluations (sap_transport_number)',
        'CREATE INDEX idx_careval_target ON carrier_evaluations (target_type)',
        'CREATE INDEX idx_careval_origin ON carrier_evaluations (origin_type)',
      ],
    })
    app.save(evalCol)

    // 2. Coleção: carrier_complaints (Reclamações com análise e tratamento)
    const complaintCol = new Collection({
      name: 'carrier_complaints',
      type: 'base',
      listRule: "@request.auth.id != ''",
      viewRule: "@request.auth.id != ''",
      createRule: "@request.auth.id != ''",
      updateRule: "@request.auth.id != ''",
      deleteRule: "@request.auth.id != ''",
      fields: [
        { name: 'complaint_number', type: 'text', required: true },
        { name: 'transport_order_number', type: 'text' },
        { name: 'sap_transport_number', type: 'text' },
        {
          name: 'category',
          type: 'select',
          required: true,
          values: [
            'RECLAMACAO_CLIENTE',
            'TRANSPORTE',
            'EXPEDICAO',
            'FATURAMENTO',
            'PORTARIA',
            'COMERCIAL',
            'SEGURANCA',
            'COMPORTAMENTO',
            'ATRASO',
            'COMUNICACAO',
            'CARGA',
            'ENTREGA',
            'DOCUMENTACAO',
            'VEICULO',
            'AVARIA',
            'OUTRO',
          ],
          maxSelect: 1,
        },
        {
          name: 'severity',
          type: 'select',
          required: true,
          values: ['BAIXA', 'MEDIA', 'ALTA', 'CRITICA'],
          maxSelect: 1,
        },
        {
          name: 'target_type',
          type: 'select',
          required: true,
          values: ['MOTORISTA', 'VEICULO', 'MOTORISTA_VEICULO', 'TRANSPORTADORA'],
          maxSelect: 1,
        },
        { name: 'driver_id', type: 'text' },
        { name: 'driver_name', type: 'text' },
        { name: 'vehicle_plate', type: 'text' },
        { name: 'carrier_name', type: 'text' },
        { name: 'customer_code', type: 'text' },
        { name: 'customer_name', type: 'text' },
        { name: 'itinerary_code', type: 'text' },
        {
          name: 'origin_type',
          type: 'select',
          required: true,
          values: [
            'CLIENTE',
            'TRANSPORTE_LOGISTICA',
            'EXPEDICAO',
            'FATURAMENTO',
            'PORTARIA',
            'COMERCIAL',
            'REPRESENTANTE_VENDEDOR',
            'SEGURANCA',
            'MOTORISTA',
            'GESTOR',
            'SISTEMA_IA',
          ],
          maxSelect: 1,
        },
        { name: 'description', type: 'text', required: true },
        { name: 'registered_by_email', type: 'text' },
        { name: 'registered_by_name', type: 'text' },
        { name: 'occurrence_date', type: 'date' },
        {
          name: 'status',
          type: 'select',
          required: true,
          values: [
            'REGISTRADA',
            'EM_ANALISE',
            'PROCEDENTE',
            'PARCIALMENTE_PROCEDENTE',
            'IMPROCEDENTE',
            'ACAO_NECESSARIA',
            'TRATADA',
            'ENCERRADA',
          ],
          maxSelect: 1,
        },
        // Tratamento e Análise
        { name: 'analyst_email', type: 'text' },
        { name: 'analyst_name', type: 'text' },
        { name: 'analysis_notes', type: 'text' },
        { name: 'driver_carrier_manifestation', type: 'text' },
        { name: 'conclusion', type: 'text' },
        { name: 'action_taken', type: 'text' },
        { name: 'resolved_at', type: 'date' },
        { name: 'evidences_json', type: 'json' },
        { name: 'audit_trail_json', type: 'json' },
        { name: 'created', type: 'autodate', onCreate: true, onUpdate: false },
        { name: 'updated', type: 'autodate', onCreate: true, onUpdate: true },
      ],
      indexes: [
        'CREATE UNIQUE INDEX idx_carcomp_num ON carrier_complaints (complaint_number)',
        'CREATE INDEX idx_carcomp_status ON carrier_complaints (status)',
        'CREATE INDEX idx_carcomp_driver ON carrier_complaints (driver_id)',
        'CREATE INDEX idx_carcomp_plate ON carrier_complaints (vehicle_plate)',
        'CREATE INDEX idx_carcomp_sap ON carrier_complaints (sap_transport_number)',
      ],
    })
    app.save(complaintCol)

    // 3. Coleção: carrier_compliments (Elogios e reconhecimentos operacionais)
    const complimentCol = new Collection({
      name: 'carrier_compliments',
      type: 'base',
      listRule: "@request.auth.id != ''",
      viewRule: "@request.auth.id != ''",
      createRule: "@request.auth.id != ''",
      updateRule: "@request.auth.id != ''",
      deleteRule: "@request.auth.id != ''",
      fields: [
        { name: 'compliment_number', type: 'text', required: true },
        { name: 'sap_transport_number', type: 'text' },
        { name: 'driver_id', type: 'text' },
        { name: 'driver_name', type: 'text' },
        { name: 'vehicle_plate', type: 'text' },
        { name: 'carrier_name', type: 'text' },
        { name: 'customer_name', type: 'text' },
        {
          name: 'category',
          type: 'select',
          required: true,
          values: [
            'ELOGIO_CLIENTE',
            'ELOGIO_EXPEDICAO',
            'BOA_ATUACAO_OCORRENCIA',
            'DISPONIBILIDADE_EXTRAORDINARIA',
            'EXCELENTE_COMUNICACAO',
            'ANTECIPACAO_PROBLEMA',
            'CUMPRIMENTO_EXCEPCIONAL',
            'COMPORTAMENTO_COLABORATIVO',
            'OUTRO',
          ],
          maxSelect: 1,
        },
        {
          name: 'origin_type',
          type: 'select',
          required: true,
          values: [
            'CLIENTE',
            'EXPEDICAO',
            'COMERCIAL',
            'TRANSPORTE_LOGISTICA',
            'GESTOR',
            'PORTARIA',
          ],
          maxSelect: 1,
        },
        { name: 'description', type: 'text', required: true },
        { name: 'registered_by_name', type: 'text' },
        { name: 'compliment_date', type: 'date' },
        { name: 'created', type: 'autodate', onCreate: true, onUpdate: false },
        { name: 'updated', type: 'autodate', onCreate: true, onUpdate: true },
      ],
      indexes: [
        'CREATE UNIQUE INDEX idx_carcomp_cnum ON carrier_compliments (compliment_number)',
        'CREATE INDEX idx_carcomp_cdriver ON carrier_compliments (driver_id)',
        'CREATE INDEX idx_carcomp_cplate ON carrier_compliments (vehicle_plate)',
      ],
    })
    app.save(complimentCol)

    // 4. Coleção: carrier_operational_history (Registro canônico de transportes históricos consolidados)
    const historyCol = new Collection({
      name: 'carrier_operational_history',
      type: 'base',
      listRule: "@request.auth.id != ''",
      viewRule: "@request.auth.id != ''",
      createRule: "@request.auth.id != ''",
      updateRule: "@request.auth.id != ''",
      deleteRule: "@request.auth.id != ''",
      fields: [
        { name: 'transport_order_number', type: 'text', required: true },
        { name: 'sap_transport_number', type: 'text' },
        { name: 'transport_date', type: 'date' },
        { name: 'driver_id', type: 'text' },
        { name: 'driver_name', type: 'text', required: true },
        { name: 'driver_document_masked', type: 'text' },
        { name: 'driver_document_full', type: 'text' },
        { name: 'vehicle_plate', type: 'text', required: true },
        { name: 'vehicle_type', type: 'text' },
        { name: 'carrier_name', type: 'text' },
        { name: 'trailer_plate', type: 'text' },
        { name: 'itinerary_code', type: 'text' },
        { name: 'itinerary_description', type: 'text' },
        { name: 'origin_plant', type: 'text' },
        { name: 'destination_city', type: 'text' },
        { name: 'destination_uf', type: 'text' },
        { name: 'region', type: 'text' },
        { name: 'customers_summary', type: 'text' },
        { name: 'discharges_count', type: 'number' },
        { name: 'weight_kg', type: 'number' },
        { name: 'weight_ton', type: 'number' },
        { name: 'products_summary', type: 'text' },
        // Horários operacionais
        { name: 'scheduled_entry', type: 'date' },
        { name: 'actual_entry', type: 'date' },
        { name: 'loading_start', type: 'date' },
        { name: 'loading_end', type: 'date' },
        { name: 'invoicing_start', type: 'date' },
        { name: 'invoicing_end', type: 'date' },
        { name: 'actual_exit', type: 'date' },
        // Tempos calculados (minutos)
        { name: 'loading_duration_min', type: 'number' },
        { name: 'invoicing_duration_min', type: 'number' },
        { name: 'internal_waiting_min', type: 'number' },
        { name: 'total_internal_dwell_min', type: 'number' },
        { name: 'internal_responsibility_min', type: 'number' },
        { name: 'carrier_responsibility_min', type: 'number' },
        // Tempos de trânsito
        { name: 'route_estimated_min', type: 'number' },
        { name: 'route_actual_min', type: 'number' },
        { name: 'delivery_estimated_at', type: 'date' },
        { name: 'delivery_actual_at', type: 'date' },
        { name: 'is_on_time', type: 'bool' },
        { name: 'delay_minutes', type: 'number' },
        { name: 'occurrences_count', type: 'number' },
        { name: 'occurrences_summary', type: 'text' },
        // Custos & Margem
        { name: 'freight_cost_driver', type: 'number' },
        { name: 'toll_cost', type: 'number' },
        { name: 'other_costs', type: 'number' },
        { name: 'total_cost', type: 'number' },
        { name: 'freight_billed_customer', type: 'number' },
        { name: 'margin_value', type: 'number' },
        { name: 'margin_pct', type: 'number' },
        // Avaliações consolidadas
        { name: 'driver_rating', type: 'number' },
        { name: 'vehicle_rating', type: 'number' },
        { name: 'complaints_count', type: 'number' },
        { name: 'complaints_procedente_count', type: 'number' },
        { name: 'compliments_count', type: 'number' },
        { name: 'non_conformities_count', type: 'number' },
        {
          name: 'final_status',
          type: 'select',
          values: [
            'CONCLUIDO',
            'EM_VIAGEM',
            'EM_EXPEDICAO',
            'CANCELADO',
            'ENCERRADO_COM_OCORRENCIA',
          ],
          maxSelect: 1,
        },
        { name: 'is_sidercentro', type: 'bool' },
        { name: 'metadata_json', type: 'json' },
        { name: 'created', type: 'autodate', onCreate: true, onUpdate: false },
        { name: 'updated', type: 'autodate', onCreate: true, onUpdate: true },
      ],
      indexes: [
        'CREATE UNIQUE INDEX idx_carhist_ord ON carrier_operational_history (transport_order_number)',
        'CREATE INDEX idx_carhist_sap ON carrier_operational_history (sap_transport_number)',
        'CREATE INDEX idx_carhist_drv ON carrier_operational_history (driver_id)',
        'CREATE INDEX idx_carhist_plt ON carrier_operational_history (vehicle_plate)',
        'CREATE INDEX idx_carhist_drv_plt ON carrier_operational_history (driver_id, vehicle_plate)',
        'CREATE INDEX idx_carhist_itin ON carrier_operational_history (itinerary_code)',
        'CREATE INDEX idx_carhist_date ON carrier_operational_history (transport_date DESC)',
        'CREATE INDEX idx_carhist_status ON carrier_operational_history (final_status)',
      ],
    })
    app.save(historyCol)
  },
  (app) => {
    try {
      app.delete(app.findCollectionByNameOrId('carrier_operational_history'))
    } catch (_) {}
    try {
      app.delete(app.findCollectionByNameOrId('carrier_compliments'))
    } catch (_) {}
    try {
      app.delete(app.findCollectionByNameOrId('carrier_complaints'))
    } catch (_) {}
    try {
      app.delete(app.findCollectionByNameOrId('carrier_evaluations'))
    } catch (_) {}
  },
)
