migrate(
  (app) => {
    const col = app.findCollectionByNameOrId('sap_customer_logistic_info')

    const customersData = [
      {
        technical_key: 'CLI-13371-REC-001',
        customer_code: '13371',
        customer_name: 'COMERCIAL DE LAMINADOS E FERROS LTDA',
        ship_to_code: 'REC-13371-01',
        ship_to_name: 'FILIAL MACEIO CENTRO LOGÍSTICO',
        cnpj: '14.288.940/0001-44',
        plant_code: '1010',
        sales_org: '1000',
        distribution_channel: '10',
        sector: '01',
        delivery_address: 'Av. Menino Marcelo, 4500 - Galpão B, Tabuleiro do Martins',
        delivery_city: 'MACEIO',
        delivery_uf: 'AL',
        delivery_cep: '57081-385',
        itinerary_code: 'AL001C',
        logistic_region: 'Nordeste Litoral',
        highest_restriction_level: 'CRITICA',
        is_active: true,
        valid_from: '2026-01-01 00:00:00.000Z',
        valid_to: '2027-12-31 23:59:59.000Z',
        sap_user: 'SAP_LOG_USER',
        origin_rfc: 'Z_RFC_TMS_INFO_CLIENTE',
        origin_table: 'ZTMS_INFO_CLIENTE',
        last_sync_date: new Date().toISOString(),
        observations:
          'Cliente com galpão em rua comercial estreita. Limite estrito de 28 t e comprimento máx de 12 m. Exige Carreta LS ou Truck.',
        material_restrictions_json: {
          minLengthM: 2.0,
          maxLengthM: 12.0,
          forbiddenLengthsM: [14.0, 15.0, 16.0, 18.0],
          maxUnitWeightKg: 3000,
          maxTotalQuantity: 50,
          requiresSpecialStrapping: true,
          prohibitMaterialMixing: false,
          stackingAllowed: true,
          maxStackingTiers: 3,
          mandatoryProtection: [
            'Lona Impermeável',
            'Calços de Madeira Tratada',
            'Cintas Protetoras de Canto',
          ],
          notes:
            'Comprimento máximo aceito 12,00m. Peças acima de 12m não manobram no portal do galpão.',
        },
        load_formation_restrictions_json: {
          exclusiveLoadOnly: false,
          allowSharedLoad: true,
          maxOrdersPerLoad: 3,
          maxDischargesPerLoad: 2,
          maxWeightPerDischargeKg: 28000,
          maxTotalWeightTons: 28.0,
          mandatoryUnloadingOrder: true,
          physicalSeparationRequired: true,
          separationCriteria: 'POR_NF',
          individualMaterialTagging: true,
          notes:
            'Limite de peso total por descarga: 28,0 t. Cargas com mais de 28 t rompem a balança interna do cliente.',
        },
        vehicle_restrictions_json: {
          allowedVehicleTypes: ['Carreta LS', 'Carreta Grade Baixa', 'Truck', 'Toco'],
          forbiddenVehicleTypes: ['Carreta Convencional', 'Bitrem', 'Rodotrem', 'Vanderleia'],
          maxLengthM: 14.0,
          maxHeightM: 4.2,
          maxWidthM: 2.6,
          maxGrossWeightTons: 40.0,
          maxAxlesCount: 5,
          mandatoryVehicleType: 'Carreta LS',
          notes: 'Carreta convencional e bitrem são PROIBIDOS na portaria. Obrigatório Carreta LS.',
        },
        access_restrictions_json: {
          hasRestrictedStreet: true,
          restrictedStreetDetails:
            'Av. Menino Marcelo - tráfego de bitrens proibido das 06:00 às 20:00',
          allowedTimeStart: '07:30',
          allowedTimeEnd: '16:30',
          urbanAccessType: 'URBANO_RESTRITO',
          unpavedRoad: false,
          requiresPriorAuthorization: true,
          authorizationLeadTimeHours: 24,
          referencePoint: 'Próximo à rotatória da Polícia Rodoviária Federal',
          accessInstructions:
            'Acesso obrigatório pela portaria lateral de carretas, apresentar autorização da portaria.',
        },
        discharge_restrictions_json: {
          dischargeType: 'Ponte Rolante',
          secondaryDischargeType: 'Munck',
          equipmentCapacityTons: 10.0,
          maxBundleWeightKg: 3000,
          dischargeSide: 'SUPERIOR_PONTE',
          requiresTarpRemoval: true,
          numberOfTieDownPoints: 8,
          historicalAvgUnloadingTimeMin: 45,
          mandatoryDischargeSequence: true,
          notes:
            'Descarga exclusivamente por Ponte Rolante. Não possui empilhadeira pesada para retirar por trás.',
        },
        scheduling_restrictions_json: {
          requiresScheduling: true,
          mandatoryBeforeDeparture: true,
          minAdvanceNoticeHours: 24,
          communicationChannel: 'WHATSAPP_PORTAL',
          contactName: 'Edson Albuquerque (Pátio Maceió)',
          contactPhone: '(82) 3345-9821',
          contactWhatsapp: '(82) 98822-1144',
          contactEmail: 'recebimento@comlaminados.com.br',
          receivingWindowStart: '08:00',
          receivingWindowEnd: '16:00',
          lunchBreakStart: '12:00',
          lunchBreakEnd: '13:30',
          allowedDays: ['SEG', 'TER', 'QUA', 'QUI', 'SEX'],
          acceptsSaturday: false,
          acceptsSunday: false,
          acceptsHoliday: false,
          arrivalToleranceMinutes: 30,
          requiresConfirmationToken: true,
          notes:
            'Agendamento prévio com protocolo obrigatório antes da liberação do veículo na saída da CIAFAL.',
        },
        documentation_restrictions_json: {
          requiredDocuments: [
            'DANFE',
            'XML',
            'Certificado de Qualidade CIAFAL',
            'Pedido do Cliente',
            'Romaneio Detalhado',
            'Comprovante de Agendamento',
          ],
          specialAuthorizationRequired: true,
          notes: 'Certificado de usina e laudo químico obrigatórios em 2 vias físicas com a carga.',
        },
        safety_driver_restrictions_json: {
          mandatoryEpiList: [
            'Capacete com jugular',
            'Óculos de proteção',
            'Botina de segurança com biqueira',
            'Colete refletivo laranja/amarelo',
          ],
          requiresSafetyTraining: true,
          trainingValidityMonths: 12,
          requiresSafetyIntegration: true,
          requiresDriverPreRegistration: true,
          minVehicleYear: 2012,
          internalRules:
            'Proibido descer do veículo sem EPI completo. Tolerância zero com calçado aberto.',
        },
        history_changelog_json: [
          {
            timestamp: '2026-08-20T10:00:00Z',
            user: 'SAP_SYNCHRONIZER',
            action: 'INITIAL_RFC_IMPORT',
            description: 'Carga inicial das restrições logísticas via RFC Z_RFC_TMS_INFO_CLIENTE',
          },
        ],
      },
      {
        technical_key: 'CLI-12487-REC-001',
        customer_code: '12487',
        customer_name: 'TUBOACOS DA AMAZONIA LTDA',
        ship_to_code: 'REC-12487-01',
        ship_to_name: 'CENTRO DE DISTRIBUIÇÃO TARUMÃ',
        cnpj: '04.551.299/0001-89',
        plant_code: '1010',
        sales_org: '1000',
        distribution_channel: '10',
        sector: '01',
        delivery_address: 'Estrada do Tarumã, 1200 - Distrito Industrial II',
        delivery_city: 'MANAUS',
        delivery_uf: 'AM',
        delivery_cep: '69041-010',
        itinerary_code: 'AM001C',
        logistic_region: 'Norte Fluvial',
        highest_restriction_level: 'RESTRITIVA',
        is_active: true,
        valid_from: '2026-01-01 00:00:00.000Z',
        valid_to: '2027-12-31 23:59:59.000Z',
        sap_user: 'SAP_LOG_USER',
        origin_rfc: 'Z_RFC_TMS_INFO_CLIENTE',
        origin_table: 'ZTMS_INFO_CLIENTE',
        last_sync_date: new Date().toISOString(),
        observations:
          'Entrega em polo fabril fluvial. Exige agendamento prévio com 48h de antecedência devido à balsa.',
        material_restrictions_json: {
          minLengthM: 1.0,
          maxLengthM: 14.0,
          forbiddenLengthsM: [],
          maxUnitWeightKg: 5000,
          maxTotalQuantity: 100,
          requiresSpecialStrapping: true,
          prohibitMaterialMixing: false,
          stackingAllowed: true,
          maxStackingTiers: 2,
          mandatoryProtection: ['Lona Reforçada', 'Separadores Plásticos Antiumidade'],
          notes: 'Proteção contra umidade fluvial mandatória para barras trefiladas.',
        },
        load_formation_restrictions_json: {
          exclusiveLoadOnly: false,
          allowSharedLoad: true,
          maxOrdersPerLoad: 5,
          maxDischargesPerLoad: 3,
          maxWeightPerDischargeKg: 32000,
          maxTotalWeightTons: 32.0,
          mandatoryUnloadingOrder: false,
          physicalSeparationRequired: true,
          separationCriteria: 'POR_PEDIDO',
          individualMaterialTagging: true,
          notes: 'Separação física com identificação visível por pedido.',
        },
        vehicle_restrictions_json: {
          allowedVehicleTypes: ['Carreta LS', 'Carreta Convencional', 'Bitrem'],
          forbiddenVehicleTypes: ['Rodotrem', 'Toco'],
          maxLengthM: 19.8,
          maxHeightM: 4.4,
          maxWidthM: 2.6,
          maxGrossWeightTons: 45.0,
          maxAxlesCount: 7,
          mandatoryVehicleType: '',
          notes: 'Permitido bitrem até 19,80m. Rodotrem não entra na balsa.',
        },
        access_restrictions_json: {
          hasRestrictedStreet: false,
          restrictedStreetDetails: '',
          allowedTimeStart: '07:00',
          allowedTimeEnd: '17:00',
          urbanAccessType: 'DISTRITO_INDUSTRIAL',
          unpavedRoad: false,
          requiresPriorAuthorization: true,
          authorizationLeadTimeHours: 48,
          referencePoint: 'Ao lado da estação aduaneira fluvial',
          accessInstructions: 'Check-in na guarita do Distrito II com número de agendamento.',
        },
        discharge_restrictions_json: {
          dischargeType: 'Ponte Rolante',
          secondaryDischargeType: 'Empilhadeira',
          equipmentCapacityTons: 15.0,
          maxBundleWeightKg: 5000,
          dischargeSide: 'SUPERIOR_PONTE',
          requiresTarpRemoval: true,
          numberOfTieDownPoints: 6,
          historicalAvgUnloadingTimeMin: 60,
          mandatoryDischargeSequence: false,
          notes: '2 pontes rolantes de 15 toneladas no vão principal.',
        },
        scheduling_restrictions_json: {
          requiresScheduling: true,
          mandatoryBeforeDeparture: true,
          minAdvanceNoticeHours: 48,
          communicationChannel: 'EMAIL_PORTAL',
          contactName: 'Gisele Amazonas',
          contactPhone: '(92) 3615-4000',
          contactWhatsapp: '(92) 99182-3311',
          contactEmail: 'logistica@tuboacos.com.br',
          receivingWindowStart: '07:00',
          receivingWindowEnd: '16:00',
          lunchBreakStart: '12:00',
          lunchBreakEnd: '13:00',
          allowedDays: ['SEG', 'TER', 'QUA', 'QUI', 'SEX'],
          acceptsSaturday: true,
          acceptsSunday: false,
          acceptsHoliday: false,
          arrivalToleranceMinutes: 60,
          requiresConfirmationToken: true,
          notes: 'Confirmação de janela via portal do cliente com código de barras.',
        },
        documentation_restrictions_json: {
          requiredDocuments: [
            'DANFE',
            'XML',
            'Certificado de Qualidade CIAFAL',
            'Romaneio Detalhado',
            'Guia Suframa',
          ],
          specialAuthorizationRequired: true,
          notes: 'Guia Suframa desembaraçada é mandatória para descarga.',
        },
        safety_driver_restrictions_json: {
          mandatoryEpiList: [
            'Capacete com jugular',
            'Óculos de proteção',
            'Botina de segurança',
            'Protetor auricular',
          ],
          requiresSafetyTraining: false,
          trainingValidityMonths: 0,
          requiresSafetyIntegration: true,
          requiresDriverPreRegistration: true,
          minVehicleYear: 2010,
          internalRules: 'Integração rápida de 15 minutos na chegada.',
        },
        history_changelog_json: [],
      },
      {
        technical_key: 'CLI-18855-REC-001',
        customer_code: '18855',
        customer_name: 'MARLI SILVA BRAZ',
        ship_to_code: 'REC-18855-01',
        ship_to_name: 'DEPOSITO MUCURI MATERIAIS',
        cnpj: '21.940.850/0001-32',
        plant_code: '1010',
        sales_org: '1000',
        distribution_channel: '10',
        sector: '01',
        delivery_address: 'Rodovia BR-101 Km 934 - Zona Rural',
        delivery_city: 'MUCURI',
        delivery_uf: 'BA',
        delivery_cep: '45930-000',
        itinerary_code: 'BA001C',
        logistic_region: 'Extremo Sul Bahia',
        highest_restriction_level: 'ALERTA',
        is_active: true,
        valid_from: '2026-01-01 00:00:00.000Z',
        valid_to: '2027-12-31 23:59:59.000Z',
        sap_user: 'SAP_LOG_USER',
        origin_rfc: 'Z_RFC_TMS_INFO_CLIENTE',
        origin_table: 'ZTMS_INFO_CLIENTE',
        last_sync_date: new Date().toISOString(),
        observations:
          'Acesso por estrada de chão batido de 800m. Requer caminhão com tração boa em dias de chuva.',
        material_restrictions_json: {
          minLengthM: 1.0,
          maxLengthM: 12.0,
          forbiddenLengthsM: [],
          maxUnitWeightKg: 2000,
          maxTotalQuantity: 40,
          requiresSpecialStrapping: false,
          prohibitMaterialMixing: false,
          stackingAllowed: true,
          maxStackingTiers: 2,
          mandatoryProtection: ['Lona'],
          notes: 'Carga bem amarrada contra trepidação da estrada de terra.',
        },
        load_formation_restrictions_json: {
          exclusiveLoadOnly: false,
          allowSharedLoad: true,
          maxOrdersPerLoad: 4,
          maxDischargesPerLoad: 3,
          maxWeightPerDischargeKg: 15000,
          maxTotalWeightTons: 15.0,
          mandatoryUnloadingOrder: false,
          physicalSeparationRequired: false,
          separationCriteria: 'POR_NF',
          individualMaterialTagging: false,
          notes: 'Capacidade de pátio para 1 veículo por vez.',
        },
        vehicle_restrictions_json: {
          allowedVehicleTypes: ['Truck', 'Toco', 'Carreta Grade Baixa'],
          forbiddenVehicleTypes: ['Bitrem', 'Rodotrem'],
          maxLengthM: 16.0,
          maxHeightM: 4.2,
          maxWidthM: 2.6,
          maxGrossWeightTons: 32.0,
          maxAxlesCount: 4,
          mandatoryVehicleType: '',
          notes: 'Carretas longas têm dificuldade de manobra no portão.',
        },
        access_restrictions_json: {
          hasRestrictedStreet: false,
          restrictedStreetDetails: '',
          allowedTimeStart: '08:00',
          allowedTimeEnd: '17:00',
          urbanAccessType: 'ACESSO_RURAL',
          unpavedRoad: true,
          requiresPriorAuthorization: false,
          authorizationLeadTimeHours: 0,
          referencePoint: 'Km 934, entrada à direita após posto de gasolina',
          accessInstructions: 'Seguir 800m de estrada de chão até o barracão azul.',
        },
        discharge_restrictions_json: {
          dischargeType: 'Munck',
          secondaryDischargeType: 'Manual',
          equipmentCapacityTons: 5.0,
          maxBundleWeightKg: 1500,
          dischargeSide: 'LATERAL_TRASEIRA',
          requiresTarpRemoval: true,
          numberOfTieDownPoints: 4,
          historicalAvgUnloadingTimeMin: 40,
          mandatoryDischargeSequence: false,
          notes: 'Descarga com caminhão munck próprio do cliente.',
        },
        scheduling_restrictions_json: {
          requiresScheduling: false,
          mandatoryBeforeDeparture: false,
          minAdvanceNoticeHours: 0,
          communicationChannel: 'TELEFONE',
          contactName: 'Braz (Proprietário)',
          contactPhone: '(73) 99911-5522',
          contactWhatsapp: '(73) 99911-5522',
          contactEmail: '',
          receivingWindowStart: '08:00',
          receivingWindowEnd: '17:00',
          lunchBreakStart: '12:00',
          lunchBreakEnd: '13:00',
          allowedDays: ['SEG', 'TER', 'QUA', 'QUI', 'SEX', 'SAB'],
          acceptsSaturday: true,
          acceptsSunday: false,
          acceptsHoliday: false,
          arrivalToleranceMinutes: 120,
          requiresConfirmationToken: false,
          notes: 'Recebe de segunda a sábado. Avisar 2h antes da chegada por WhatsApp.',
        },
        documentation_restrictions_json: {
          requiredDocuments: ['DANFE', 'Certificado de Qualidade CIAFAL'],
          specialAuthorizationRequired: false,
          notes: 'DANFE assinada no ato pelo Sr. Braz ou encarregado.',
        },
        safety_driver_restrictions_json: {
          mandatoryEpiList: ['Botina de segurança', 'Óculos'],
          requiresSafetyTraining: false,
          trainingValidityMonths: 0,
          requiresSafetyIntegration: false,
          requiresDriverPreRegistration: false,
          minVehicleYear: 2000,
          internalRules: 'Uso obrigatório de calçado fechado no pátio.',
        },
        history_changelog_json: [],
      },
      {
        technical_key: 'CLI-13707-REC-001',
        customer_code: '13707',
        customer_name: 'PETRAL COMERCIO DE FERRO E ACO LTDA',
        ship_to_code: 'REC-13707-01',
        ship_to_name: 'UNIDADE INDUSTRIAL FORTALEZA',
        cnpj: '07.822.415/0001-90',
        plant_code: '1010',
        sales_org: '1000',
        distribution_channel: '10',
        sector: '01',
        delivery_address: 'Av. Francisco Sá, 3800 - Barra do Ceará',
        delivery_city: 'FORTALEZA',
        delivery_uf: 'CE',
        delivery_cep: '60310-002',
        itinerary_code: 'CE001C',
        logistic_region: 'Ceará Litoral',
        highest_restriction_level: 'INFORMATIVA',
        is_active: true,
        valid_from: '2026-01-01 00:00:00.000Z',
        valid_to: '2027-12-31 23:59:59.000Z',
        sap_user: 'SAP_LOG_USER',
        origin_rfc: 'Z_RFC_TMS_INFO_CLIENTE',
        origin_table: 'ZTMS_INFO_CLIENTE',
        last_sync_date: new Date().toISOString(),
        observations:
          'Pátio amplo, estrutura com ponte rolante dupla e doca rebaixada. Sem restrições severas de veículo.',
        material_restrictions_json: {
          minLengthM: 1.0,
          maxLengthM: 14.0,
          forbiddenLengthsM: [],
          maxUnitWeightKg: 6000,
          maxTotalQuantity: 80,
          requiresSpecialStrapping: false,
          prohibitMaterialMixing: false,
          stackingAllowed: true,
          maxStackingTiers: 4,
          mandatoryProtection: ['Lona'],
          notes: 'Armazenamento em galpão coberto climatizado.',
        },
        load_formation_restrictions_json: {
          exclusiveLoadOnly: false,
          allowSharedLoad: true,
          maxOrdersPerLoad: 6,
          maxDischargesPerLoad: 4,
          maxWeightPerDischargeKg: 35000,
          maxTotalWeightTons: 35.0,
          mandatoryUnloadingOrder: false,
          physicalSeparationRequired: false,
          separationCriteria: 'POR_NF',
          individualMaterialTagging: false,
          notes: 'Excelente estrutura para recebimento rápido.',
        },
        vehicle_restrictions_json: {
          allowedVehicleTypes: [
            'Carreta LS',
            'Carreta Grade Baixa',
            'Carreta Convencional',
            'Bitrem',
            'Truck',
          ],
          forbiddenVehicleTypes: ['Rodotrem'],
          maxLengthM: 19.8,
          maxHeightM: 4.4,
          maxWidthM: 2.6,
          maxGrossWeightTons: 45.0,
          maxAxlesCount: 7,
          mandatoryVehicleType: '',
          notes: 'Aceita qualquer tipo de carreta convencional ou LS.',
        },
        access_restrictions_json: {
          hasRestrictedStreet: false,
          restrictedStreetDetails: '',
          allowedTimeStart: '07:30',
          allowedTimeEnd: '17:30',
          urbanAccessType: 'AVENIDA_COMERCIAL',
          unpavedRoad: false,
          requiresPriorAuthorization: false,
          authorizationLeadTimeHours: 0,
          referencePoint: 'Em frente ao terminal de ônibus',
          accessInstructions: 'Entrada livre pelo portão 02 de carretas.',
        },
        discharge_restrictions_json: {
          dischargeType: 'Ponte Rolante',
          secondaryDischargeType: 'Empilhadeira',
          equipmentCapacityTons: 20.0,
          maxBundleWeightKg: 6000,
          dischargeSide: 'SUPERIOR_PONTE',
          requiresTarpRemoval: true,
          numberOfTieDownPoints: 6,
          historicalAvgUnloadingTimeMin: 35,
          mandatoryDischargeSequence: false,
          notes: 'Duas pontes de 20t com gancho e eletroímã.',
        },
        scheduling_restrictions_json: {
          requiresScheduling: false,
          mandatoryBeforeDeparture: false,
          minAdvanceNoticeHours: 0,
          communicationChannel: 'WHATSAPP',
          contactName: 'Rogério Almoxarifado',
          contactPhone: '(85) 3214-9988',
          contactWhatsapp: '(85) 98777-6655',
          contactEmail: 'recebimento@petralferro.com.br',
          receivingWindowStart: '07:30',
          receivingWindowEnd: '17:00',
          lunchBreakStart: '12:00',
          lunchBreakEnd: '13:00',
          allowedDays: ['SEG', 'TER', 'QUA', 'QUI', 'SEX'],
          acceptsSaturday: false,
          acceptsSunday: false,
          acceptsHoliday: false,
          arrivalToleranceMinutes: 60,
          requiresConfirmationToken: false,
          notes: 'Atendimento por ordem de chegada com fila prioritária para carretas completas.',
        },
        documentation_restrictions_json: {
          requiredDocuments: ['DANFE', 'XML', 'Certificado de Qualidade CIAFAL'],
          specialAuthorizationRequired: false,
          notes: 'DANFE com chave de acesso legível.',
        },
        safety_driver_restrictions_json: {
          mandatoryEpiList: [
            'Capacete com jugular',
            'Óculos de proteção',
            'Botina de segurança',
            'Colete',
          ],
          requiresSafetyTraining: false,
          trainingValidityMonths: 0,
          requiresSafetyIntegration: false,
          requiresDriverPreRegistration: false,
          minVehicleYear: 2008,
          internalRules: 'Uso obrigatório de EPIs completos na área de descarga.',
        },
        history_changelog_json: [],
      },
    ]

    for (const c of customersData) {
      try {
        app.findFirstRecordByData('sap_customer_logistic_info', 'technical_key', c.technical_key)
      } catch (_) {
        const rec = new Record(col)
        for (const [k, v] of Object.entries(c)) {
          rec.set(k, v)
        }
        app.save(rec)
      }
    }
  },
  (app) => {
    try {
      const col = app.findCollectionByNameOrId('sap_customer_logistic_info')
      app.truncateCollection(col)
    } catch (_) {}
  },
)
