migrate(
  (app) => {
    // Coleção aditiva: route_additions (Seção 20 do requisito)
    const col = new Collection({
      name: 'route_additions',
      type: 'base',
      listRule: '',
      viewRule: '',
      createRule: "@request.auth.id != ''",
      updateRule: "@request.auth.id != ''",
      deleteRule: "@request.auth.id != ''",
      fields: [
        { name: 'load_id', type: 'text', required: true },
        { name: 'cargo_number', type: 'text' },
        { name: 'transport_number', type: 'text' },
        { name: 'original_itinerary_id', type: 'text', required: true },
        { name: 'original_itinerary_description', type: 'text' },
        { name: 'added_itinerary_id', type: 'text', required: true },
        { name: 'added_itinerary_description', type: 'text' },
        { name: 'added_route_id', type: 'text' },
        { name: 'customer_code', type: 'text' },
        { name: 'customer_name', type: 'text' },
        { name: 'destination_city', type: 'text' },
        { name: 'destination_uf', type: 'text' },
        { name: 'order_numbers_json', type: 'json' },
        { name: 'reason_code', type: 'text', required: true },
        { name: 'reason_description', type: 'text', required: true },
        { name: 'user_observation', type: 'text' },
        { name: 'ai_analysis', type: 'text' },
        {
          name: 'ai_user_alignment',
          type: 'select',
          values: ['Coerente', 'Parcialmente coerente', 'Divergente', 'Dados insuficientes'],
          maxSelect: 1,
        },
        {
          name: 'ai_risk_level',
          type: 'select',
          values: ['FAVORAVEL', 'MODERADO', 'ALTO_IMPACTO_DESFAVORAVEL'],
          maxSelect: 1,
        },
        { name: 'ai_alert_flag', type: 'bool' },
        { name: 'ai_alert_message', type: 'text' },
        { name: 'distance_before', type: 'number' },
        { name: 'distance_after', type: 'number' },
        { name: 'additional_distance', type: 'number' },
        { name: 'additional_time_hours', type: 'number' },
        { name: 'weight_before', type: 'number' },
        { name: 'weight_after', type: 'number' },
        { name: 'occupancy_before', type: 'number' },
        { name: 'occupancy_after', type: 'number' },
        { name: 'vehicle_capacity_kg', type: 'number' },
        { name: 'freight_before', type: 'number' },
        { name: 'freight_after', type: 'number' },
        { name: 'toll_before', type: 'number' },
        { name: 'toll_after', type: 'number' },
        { name: 'cost_per_ton_before', type: 'number' },
        { name: 'cost_per_ton_after', type: 'number' },
        { name: 'deliveries_before', type: 'number' },
        { name: 'deliveries_after', type: 'number' },
        { name: 'clients_before', type: 'number' },
        { name: 'clients_after', type: 'number' },
        { name: 'status', type: 'select', values: ['ATIVA', 'REMOVIDA'], maxSelect: 1 },
        { name: 'created_by', type: 'text' },
        { name: 'created_by_role', type: 'text' },
        { name: 'created_at_dt', type: 'date' },
        { name: 'removed_by', type: 'text' },
        { name: 'removed_by_role', type: 'text' },
        { name: 'removed_at_dt', type: 'date' },
        { name: 'removal_reason', type: 'text' },
        { name: 'created', type: 'autodate', onCreate: true, onUpdate: false },
        { name: 'updated', type: 'autodate', onCreate: true, onUpdate: true },
      ],
      indexes: [
        'CREATE INDEX idx_ra_load_id ON route_additions (load_id)',
        'CREATE INDEX idx_ra_orig_itin ON route_additions (original_itinerary_id)',
        'CREATE INDEX idx_ra_add_itin ON route_additions (added_itinerary_id)',
        'CREATE INDEX idx_ra_reason ON route_additions (reason_code)',
        'CREATE INDEX idx_ra_status ON route_additions (status)',
        'CREATE INDEX idx_ra_created_by ON route_additions (created_by)',
      ],
    })
    app.save(col)
  },
  (app) => {
    try {
      const col = app.findCollectionByNameOrId('route_additions')
      app.delete(col)
    } catch (_) {}
  },
)
